MetricArts.JnJ.Mantenciones.Web/Models/Mantenedores/PlantillasPDF/PlantillasPDFFormModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;

namespace MetricArts.JnJ.Mantenciones.Models.Mantenedores.PlantillasPDF
{
    public class PlantillasPDFFormModel
    {
        [DisplayName("Nombre Plantilla")]
        public string Nombre { get; set; }

        [DisplayName("Descripción")]
        public string Descripcion { get; set; }

        [DisplayName("Cuerpo Plantilla (Puede agregar TAGS en el caso sea necesario generar valores dinámicos en el texto)")]
        public string cuerpoHTML { get; set; }

        public Guid IdTipoNotificacion { get; set; }

        public Guid IdPlantilla { get; set; }

        public string userName { get; set; }
    }
}

MetricArts.JnJ.Mantenciones.Web/Models/Mantenedores/PlantillasPDF/PlantillasPDFViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MetricArts.JnJ.Mantenciones.Core;

namespace MetricArts.JnJ.Mantenciones.Models.Mantenedores.PlantillasPDF
{
    public class PlantillasPDFViewModel
    {
        private MantencionesDataContext db = new MantencionesDataContext()
                .WithConnectionStringFromConfiguration();
        public PlantillasPDFFormModel FORM { get; set; }
        public IEnumerable<PDFTemplate> PlantillasPDF { get; set; }
        public PDFTemplate plantillaPDF { get; set; }
        public IEnumerable<SelectListItem> TiposNotificacion { get; set; }
        public IEnumerable<MapTag> Tags { get; set; }

        public PlantillasPDFViewModel() 
        {
            PlantillasPDF = db.PDFTemplates.OrderBy(x => x.Nombre);
        }

        public PlantillasPDFViewModel(string userName)
        {
            TiposNotificacion = db.TipoNotificacions.OrderBy(x => x.Codigo).Select(x => new SelectListItem()
            {
                Text = x.Nombre,
                Value = x.IdTipoNotificacion.ToString()
            });

            Tags = db.MapTags;
        }

        public PlantillasPDFViewModel(Guid idPlantilla)
        {
            plantillaPDF = db.PDFTemplates.Single(x => x.IdPDFTemplate == idPlantilla);
            FORM = new PlantillasPDFFormModel();
            FORM.IdPlantilla = plantillaPDF.IdPDFTemplate;
            FORM.Nombre = plantillaPDF.Nombre;
            FORM.Descripcion = plantillaPDF.Descripcion;
            FORM.cuerpoHTML = plantillaPDF.CuerpoHTML;
            FORM.IdTipoNotificacion = plantillaPDF.IdTipoNotificacion.Value;

            TiposNotificacion = db.TipoNotificacions.OrderBy(x => x.Codigo).Select(x => new SelectListItem()
            {
                Text = x.Nombre,
                Value = x.IdTipoNotificacion.ToString()
            });

            Tags = db.MapTags;
        }

        public PlantillasPDFViewModel(PlantillasPDFFormModel form)
        {
            FORM = form;
        }

        public string getPlantillaHtml(Guid IdPlantilla)
        {
            return db.PDFTemplates.Single(x => x.IdPDFTemplate == IdPlantilla).CuerpoHTML;
        }

        /**
        * Funciones CRUD
       **/

        public void create()
        {
            TipoNotificacion t = db.TipoNotificacions.Single(x => x.IdTipoNotificacion == FORM.IdTipoNotificacion);

            PDFTemplate nuevo = new PDFTemplate
            {
                IdPDFTemplate = Guid.NewGuid(),
                TipoNotificacion = t,
                Nombre = FORM.Nombre,
                Descripcion = FORM.Descripcion,
                CuerpoHTML = FORM.cuerpoHTML,
                FechaCreacion = DateTime.Now,
                CreadoPor = FORM.userName
            };
            db.PDFTemplates.InsertOnSubmit(nuevo);
            db.SubmitChanges();
        }

        public void update()
        {
            TipoNotificacion t = db.TipoNotificacions.Single(x => x.IdTipoNotificacion == FORM.IdTipoNotificacion);

            PDFTemplate p = db.PDFTemplates.Single(x => x.IdPDFTemplate == FORM.IdPlantilla);
            p.TipoNotificacion = t;
            p.Nombre = FORM.Nombre;
            p.Descripcion = FORM.Descripcion;
            p.CuerpoHTML = FORM.cuerpoHTML;
            db.SubmitChanges();
        }

        public void delete()
        {
            PDFTemplate p = db.PDFTemplates.Single(x => x.IdPDFTemplate == FORM.IdPlantilla);
            db.PDFTemplates.DeleteOnSubmit(p);
            db.SubmitChanges();
        }

        /**
         * FIN Funciones CRUD
        **/
    }
}

MetricArts.JnJ.Mantenciones.Web/Controllers/Mantenedores/PlantillasPDFController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MetricArts.JnJ.Mantenciones.Models.Mantenedores.PlantillasPDF;

namespace MetricArts.JnJ.Mantenciones.Controllers.Mantenedores
{
    public class PlantillasPDFController : Controller
    {
        //
        // GET: /PlantillasPDF/

        public ActionResult Index()
        {
            PlantillasPDFViewModel model = new PlantillasPDFViewModel();
            return View(model);
        }

        //
        // GET: /PlantillasPDF/CrearNuevo
        [HttpGet]
        public ActionResult CrearNuevo()
        {
            PlantillasPDFViewModel model = new PlantillasPDFViewModel(User.Identity.Name);
            return View(model);
        }

        //
        // POST: /PlantillasPDF/CrearNuevo
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult CrearNuevo(PlantillasPDFFormModel form)
        {
            PlantillasPDFViewModel model = new PlantillasPDFViewModel(form);

            try
            {
                if (ModelState.IsValid)
                {
                    form.userName = User.Identity.Name;
                    model.create();
                    Mensaje = "Se ha creado la plantilla con éxito.";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception e)
            {
                model = new PlantillasPDFViewModel(User.Identity.Name);
                Mensaje = "No se han podido guardar los cambios. Intente nuevamente. Si el problema persiste, favor contactarse con servicio técnico.";
            }
            return View(model);
        }

        //
        // GET: /PlantillasPDF/Editar
        [HttpGet]
        public ActionResult Editar(Guid IdPlantilla)
        {
            PlantillasPDFViewModel model = new PlantillasPDFViewModel(IdPlantilla);
            return View(model);
        }

        //
        // POST: /PlantillasPDF/Editar
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Editar(PlantillasPDFFormModel form)
        {
            PlantillasPDFViewModel model = new PlantillasPDFViewModel(form);

            try
            {
                if (ModelState.IsValid)
                {
                    form.userName = User.Identity.Name;
                    model.update();
                    Mensaje = "Se han guardado los cambios con éxito.";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception e)
            {
                model = new PlantillasPDFViewModel(form.IdPlantilla);
                Mensaje = "No se han podido guardar los cambios. Intente nuevamente. Si el problema persiste, favor contactarse con servicio técnico.";
            }
            return View(model);
        }

        //
        // GET: /PlantillasPDF/Editar
        [HttpGet]
        public ActionResult Eliminar(Guid IdPlantilla)
        {
            PlantillasPDFViewModel model = new PlantillasPDFViewModel(IdPlantilla);
            model.delete();
            Mensaje = "Se ha eliminado la plantilla con éxito.";
            return RedirectToAction("Index");
        }

        //
        // GET: /PlantillasPDF/ObtenerPlantillaHtml
        [HttpGet]
        public ActionResult ObtenerPlantillaHtml(Guid IdPlantilla)
        {
            PlantillasPDFViewModel model = new PlantillasPDFViewModel(IdPlantilla);
            string msg = model.getPlantillaHtml(IdPlantilla);
            return Content(msg);
        }

        public string Mensaje
        {
            set
            {
                TempData["Mensaje"] = value;
            }
        }

    }
}

MetricArts.JnJ.Mantenciones.Web/Views/PlantillasPDF/CrearNuevo.cshtml
@model MetricArts.JnJ.Mantenciones.Models.Mantenedores.PlantillasPDF.PlantillasPDFViewModel
@{
    ViewBag.Title = "Crear Nueva Plantilla PDF";
}

<div class="row-fluid">
				<ol class="breadcrumb">
					<li><a href="@Url.Action("Index", "Home")">Inicio</a></li>
					<li><a href="@Url.Action("Index", "Mantenedores")">Mantenedores</a></li>
					<li><a href="@Url.Action("Index", "PlantillasPDF")">Plantillas PDF</a></li>
					<li><a href="@Url.Action("CrearNuevo", "PlantillasPDF")">Nuevo</a></li>
				</ol>
			</div>

			<section>
				<div class="row-fluid">
					<h3>Crear Nueva Plantilla PDF</h3>
				</div>
                @if (TempData["Mensaje"] != null && !String.IsNullOrEmpty(TempData["Mensaje"].ToString()))
                {
                <div class="alert alert-warning alert-dismissible fadeOutMantenedor" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <strong>@(TempData["Mensaje"])</strong>
                </div>
                }
                <br />
                <form action="@Url.Action("CrearNuevo", "PlantillasPDF")" method="POST" class="form-horizontal">
				<div class="row-fluid">
						<div class="form-group">
							<label class="col-sm-4 control-label">@Html.LabelFor(x => x.FORM.Nombre)</label>
							<div class="col-sm-6">
                                @Html.TextBoxFor(x => x.FORM.Nombre, new { @class = "form-control input-sm" })
							</div>
						</div>
                        <div class="form-group">
							<label class="col-sm-4 control-label">@Html.LabelFor(x => x.FORM.Descripcion)</label>
							<div class="col-sm-6">
                                @Html.TextBoxFor(x => x.FORM.Descripcion, new { @class = "form-control input-sm" })
							</div>
						</div>
                    <div class="form-group">
							<label class="col-sm-4 control-label">@Html.LabelFor(x => x.FORM.IdTipoNotificacion)</label>
							<div class="col-sm-6">
                                @Html.DropDownListFor(x => x.FORM.IdTipoNotificacion, Model.TiposNotificacion, "Seleccione un Tipo de Notificación", new { @class = "form-control input-sm" })
							</div>
						</div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">@Html.LabelFor(x => x.FORM.cuerpoHTML)</label>
					    <br />
                        <div class="row-fluid">
                            @foreach(var item in Model.Tags) 
                            {
                                <button type="button" name="boton-tag" value="@(item.TagLlave)" data-toggle="tooltip" data-placement="bottom" title="@(item.Descripcion)" class="btn btn-danger">
                                    @(item.NombreTag)
					            </button>
                            }
                        </div>
                        <br />
                        <div class="col-sm-12">
                            @Html.TextAreaFor(x => x.FORM.cuerpoHTML, new { @name = "editor", @id = "editor", @rows = "70", @cols = "80" })
                        </div>
				    </div>							
				</div>
				<div class="row">
					<div class="col-md-6 col-md-offset-4">
						<input type="submit" class="btn btn-success pull-right" value="Guardar" />
                        <a href="@Url.Action("Index", "PlantillasPDF")" class="btn btn-primary">Cancelar</a>
					</div>
                    
				</div>
                </form>
			</section>
<script type="text/javascript">
    CKEDITOR_BASEPATH = "@Url.Content("~/Scripts/ckeditor/")";
</script>
@Scripts.Render("~/bundles/external/text-editor/js")
@Scripts.Render("~/bundles/custom/mantenedores/plantillas-pdf/crear")
<script type="text/javascript">
    $(document).ready(function () {
        init();
    });
</script>

MetricArts.JnJ.Mantenciones.Web/Views/PlantillasPDF/Editar.cshtml
@model MetricArts.JnJ.Mantenciones.Models.Mantenedores.PlantillasPDF.PlantillasPDFViewModel
@{
    ViewBag.Title = "Editar Plantilla PDF";
}

<div class="row-fluid">
				<ol class="breadcrumb">
					<li><a href="@Url.Action("Index", "Home")">Inicio</a></li>
					<li><a href="@Url.Action("Index", "Mantenedores")">Mantenedores</a></li>
					<li><a href="@Url.Action("Index", "PlantillasPDF")">Plantillas PDF</a></li>
				</ol>
			</div>

			<section>
				<div class="row-fluid">
					<h3>Editar Plantilla PDF</h3>
				</div>
                @if (TempData["Mensaje"] != null && !String.IsNullOrEmpty(TempData["Mensaje"].ToString()))
                {
                <div class="alert alert-warning alert-dismissible fadeOutMantenedor" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <strong>@(TempData["Mensaje"])</strong>
                </div>
                }
                <br />
                <form action="@Url.Action("Editar", "PlantillasPDF")" method="POST" class="form-horizontal">
                    @Html.HiddenFor(x => x.FORM.IdPlantilla)
				<div class="row-fluid">
						<div class="form-group">
							<label class="col-sm-4 control-label">@Html.LabelFor(x => x.FORM.Nombre)</label>
							<div class="col-sm-6">
                                @Html.TextBoxFor(x => x.FORM.Nombre, new { @class = "form-control input-sm" })
							</div>
						</div>
                        <div class="form-group">
							<label class="col-sm-4 control-label">@Html.LabelFor(x => x.FORM.Descripcion)</label>
							<div class="col-sm-6">
                                @Html.TextBoxFor(x => x.FORM.Descripcion, new { @class = "form-control input-sm" })
							</div>
						</div>
                    <div class="form-group">
							<label class="col-sm-4 control-label">@Html.LabelFor(x => x.FORM.IdTipoNotificacion)</label>
							<div class="col-sm-6">
                                @Html.DropDownListFor(x => x.FORM.IdTipoNotificacion, Model.TiposNotificacion, "Seleccione un Tipo de Notificación", new { @class = "form-control input-sm" })
							</div>
						</div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">@Html.LabelFor(x => x.FORM.cuerpoHTML)</label>
                        <br />
                        <div class="row-fluid">
                            @foreach(var item in Model.Tags) 
                            {
                                <button type="button" name="boton-tag" value="@(item.TagLlave)" data-toggle="tooltip" data-placement="bottom" title="@(item.Descripcion)" class="btn btn-danger">
                                    @(item.NombreTag)
					            </button>
                            }
                        </div>
                        <br />
					    <div class="col-sm-12">
                            @Html.TextAreaFor(x => x.FORM.cuerpoHTML, new { @name = "editor", @id = "editor", @rows = "70", @cols = "80" })
                        </div>
				    </div>							
				</div>
				<div class="row">
					<div class="col-md-6 col-md-offset-4">
						<input type="submit" class="btn btn-success pull-right" value="Guardar" />
                        <a href="@Url.Action("Index", "PlantillasPDF")" class="btn btn-primary">Cancelar</a>
					</div>
                    
				</div>
                </form>
			</section>
<script type="text/javascript">
    CKEDITOR_BASEPATH = "@Url.Content("~/Scripts/ckeditor/")";
</script>
@Scripts.Render("~/bundles/external/text-editor/js")
@Scripts.Render("~/bundles/custom/mantenedores/plantillas-pdf/editar")
<script type="text/javascript">
    $(document).ready(function () {
        init();
    });
</script>

MetricArts.JnJ.Mantenciones.Web/Views/PlantillasPDF/Index.cshtml
@model MetricArts.JnJ.Mantenciones.Models.Mantenedores.PlantillasPDF.PlantillasPDFViewModel
@{
    ViewBag.Title = "Listado Plantillas PDF";
}
<section class="container-fluid">
    <article>
        <div class="row">
		    <ol class="breadcrumb">
			    <li><a href="@Url.Action("Index", "Home")">Inicio</a></li>
			    <li><a href="@Url.Action("Index", "Mantenedores")">Mantenedores</a></li>
				<li><a href="@Url.Action("Index", "PlantillasPDF")">Plantillas PDF</a></li>
			</ol>
		</div>

        <article>
		    <div class="bs-callout bs-callout-JJ">
                <legend>Plantillas PDF</legend>
                <a href="@Url.Action("CrearNuevo", "PlantillasPDF")" data-toggle="confirmation"  title="Nueva Plantilla" class="btn btn-success">
                    <span class='glyphicon glyphicon-plus-sign'></span> Crear Nuevo
                </a>

                <button class="btn btn-primary" type="button">
			        Cantidad Total <span class="badge">@Model.PlantillasPDF.Count()</span>
				</button>
		    </div>
		</article>

        <br />
        @if (TempData["Mensaje"] != null && !String.IsNullOrEmpty(TempData["Mensaje"].ToString()))
        {
            <div class="alert alert-success alert-dismissible fadeOutMantenedor" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <strong>@(TempData["Mensaje"])</strong>
            </div>
        }
        <br />
        <div class="row">
            <div class="table-responsive">                            
                <table id="listado-mantenedor" class="table table-striped table-condensed display">
                    <thead>
                        <tr>
                            <th>@Html.DisplayName("Nombre")</th>
                            <th>@Html.DisplayName("Descripción")</th>
                            <th>@Html.DisplayName("Tipo Notificación")</th>
                            <th>@Html.DisplayName("Cuerpo PDF")</th>
                            <th>Editar</th>
                            <th>Eliminar</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.PlantillasPDF)
                        {
                            <tr>
                                <td>@Html.DisplayFor(modelItem => item.Nombre)</td>
                                <td>@Html.DisplayFor(modelItem => item.Descripcion)</td>
                                <td>@Html.DisplayFor(modelItem => item.TipoNotificacion.Nombre)</td>
                                <td><button type='button' id=' @(item.IdPDFTemplate)' name='pdf-preview' data-toggle='tooltip' data-placement='bottom' title='Previsualizar PDF' class='btn btn-default btn-modal-trigger'><span class='glyphicon glyphicon-new-window'></span></button></td>
                                <td><a href="@Url.Action("Editar", "PlantillasPDF", new { IdPlantilla = item.IdPDFTemplate })" class="btn btn-default"><span class='glyphicon glyphicon-edit'></span></a></td>
                                <td>
                                    <a href="@Url.Action("Eliminar", "PlantillasPDF", new { IdPlantilla = item.IdPDFTemplate })" class="btn btn-default" onclick="if(!confirm('Está a punto de eliminar esta plantilla.\n¿Desea continuar?.')) return false;"><span class='glyphicon glyphicon-trash'></span></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
			</div>
		</div>
    </article>
</section>

<div class="modal fade" id="ModalPreviewPlantilla" tabindex="-1" role="dialog" aria-labelledby="">
			<div class="modal-dialog" role="document">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						</button>
						<h4 class="modal-title" id="myModalLabel"><span id="titulo-modal"></span></h4>
					</div>
					<div id="contenido-modal" class="modal-body">
						
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
					</div>
				</div>
			</div>
		</div>

@Scripts.Render("~/bundles/custom/mantenedores/plantillas-pdf/listado")
<script type="text/javascript">
    $(document).ready(function () {
        init('@Url.Action("ObtenerPlantillaHtml", "PlantillasPDF")');
    });
</script>