MetricArts.JnJ.Mantenciones.Web/Models/Mantenedores/Repuestos/RepuestosFormModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;

namespace MetricArts.JnJ.Mantenciones.Models.Mantenedores.Repuestos
{
    public class RepuestosFormModel
    {
        [DisplayName("Categoría")]
        public string Categoria { get; set; }

        [DisplayName("Código")]
        public string Codigo { get; set; }

        [DisplayName("Cantidad")]
        public int Cantidad { get; set; }

        [DisplayName("Descripción")]
        public string Descripcion { get; set; }

        public Guid IdRepuesto { get; set; }

        public string userName { get; set; }
    }
}

MetricArts.JnJ.Mantenciones.Web/Models/Mantenedores/Repuestos/RepuestosViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MetricArts.JnJ.Mantenciones.Core;

namespace MetricArts.JnJ.Mantenciones.Models.Mantenedores.Repuestos
{
    public class RepuestosViewModel
    {
        private MantencionesDataContext db = new MantencionesDataContext()
                .WithConnectionStringFromConfiguration();
        public RepuestosFormModel FORM { get; set; }
        public IEnumerable<Repuesto> Repuestos { get; set; }
        public Repuesto repuesto { get; set; }
        public List<SelectListItem> Categorias { get; set; }

        public RepuestosViewModel() 
        {
            Repuestos = db.Repuestos.OrderBy(x => x.Codigo);
        }

        public RepuestosViewModel(string userName)
        {
        }

        public RepuestosViewModel(Guid idRepuesto)
        {
            repuesto = db.Repuestos.Single(x => x.IdRepuesto == idRepuesto);
            FORM = new RepuestosFormModel();
            FORM.Categoria = repuesto.Categoria;
            FORM.Codigo = repuesto.Codigo;
            FORM.Cantidad = repuesto.Cantidad;
            FORM.Descripcion = repuesto.Descripcion;
            FORM.IdRepuesto = repuesto.IdRepuesto;

            Categorias = new List<SelectListItem>();

            var item1 = new SelectListItem()
            {
                Text = "Requerido",
                Value = "Requerido"
            };

            var item2 = new SelectListItem()
            {
                Text = "Recomendado",
                Value = "Recomendado"
            };

            Categorias.Add(item1);
            Categorias.Add(item2);
        }

        public RepuestosViewModel(RepuestosFormModel form)
        {
            FORM = form;
        }

        /**
         * Funciones CRUD
        **/

        public void create() 
        {
            Repuesto nueva = new Repuesto
            {
                IdRepuesto = Guid.NewGuid(),
                Categoria = FORM.Categoria,
                Codigo = FORM.Codigo,
                Cantidad = FORM.Cantidad,
                Descripcion = FORM.Descripcion
            };
            db.Repuestos.InsertOnSubmit(nueva);
            db.SubmitChanges();
        }

        public void update()
        {
            Repuesto r = db.Repuestos.Single(x => x.IdRepuesto == FORM.IdRepuesto);
            r.Categoria = FORM.Categoria;
            r.Codigo = FORM.Codigo;
            r.Cantidad = FORM.Cantidad;
            r.Descripcion = FORM.Descripcion;
            db.SubmitChanges();
        }

        public void delete()
        {
            Repuesto r = db.Repuestos.Single(x => x.IdRepuesto == FORM.IdRepuesto);
            db.Repuestos.DeleteOnSubmit(r);
            db.SubmitChanges();
        }

        /**
         * FIN Funciones CRUD
        **/
    }
}

MetricArts.JnJ.Mantenciones.Web/Controllers/Mantenedores/RepuestosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MetricArts.JnJ.Mantenciones.Models.Mantenedores.Repuestos;

namespace MetricArts.JnJ.Mantenciones.Controllers.Mantenedores
{
    public class RepuestosController : Controller
    {
        //
        // GET: /Repuestos/

        public ActionResult Index()
        {
            RepuestosViewModel model = new RepuestosViewModel();
            return View(model);
        }

        //
        // GET: /Repuestos/CrearNuevo
        [HttpGet]
        public ActionResult CrearNuevo()
        {
            RepuestosViewModel model = new RepuestosViewModel(User.Identity.Name);
            return View(model);
        }

        //
        // POST: /Repuestos/CrearNuevo
        [HttpPost]
        public ActionResult CrearNuevo(RepuestosFormModel form)
        {
            RepuestosViewModel model = new RepuestosViewModel(form);

            try
            {
                if (ModelState.IsValid)
                {
                    form.userName = User.Identity.Name;
                    model.create();
                    Mensaje = "Se ha creado el repuesto con éxito.";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception e)
            {
                model = new RepuestosViewModel(User.Identity.Name);
                Mensaje = "No se han podido guardar los cambios. Intente nuevamente. Si el problema persiste, favor contactarse con servicio técnico.";
            }
            return View(model);
        }

        //
        // GET: /Repuestos/Editar
        [HttpGet]
        public ActionResult Editar(Guid IdRepuesto)
        {
            RepuestosViewModel model = new RepuestosViewModel(IdRepuesto);
            return View(model);
        }

        //
        // POST: /Repuestos/Editar
        [HttpPost]
        public ActionResult Editar(RepuestosFormModel form)
        {
            RepuestosViewModel model = new RepuestosViewModel(form);

            try
            {
                if (ModelState.IsValid)
                {
                    form.userName = User.Identity.Name;
                    model.update();
                    Mensaje = "Se han guardado los cambios con éxito.";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception e)
            {
                model = new RepuestosViewModel(form.IdRepuesto);
                Mensaje = "No se han podido guardar los cambios. Intente nuevamente. Si el problema persiste, favor contactarse con servicio técnico.";
            }
            return View(model);
        }

        //
        // GET: /Repuestos/Editar
        [HttpGet]
        public ActionResult Eliminar(Guid IdRepuesto)
        {
            RepuestosViewModel model = new RepuestosViewModel(IdRepuesto);
            model.delete();
            Mensaje = "Se ha eliminado el repuesto con éxito.";
            return RedirectToAction("Index");
        }

        public string Mensaje
        {
            set
            {
                TempData["Mensaje"] = value;
            }
        }
    }
}

MetricArts.JnJ.Mantenciones.Web/Controllers/ServicioConsultaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MetricArts.JnJ.Mantenciones.Core;
using MetricArts.JnJ.Mantenciones.Helpers;

namespace MetricArts.JnJ.Mantenciones.Controllers
{
    public class ServicioConsultaController : Controller
    {
        protected MantencionesDataContext db = new MantencionesDataContext()
                .WithConnectionStringFromConfiguration();

        //
        // GET: /ServicioConsulta/ObtenerClientes
        public ActionResult ObtenerClientes(Guid franquiciaId)
        {
            try
            {
                if (franquiciaId != null)
                {
                    IEnumerable<SelectListItem> clientes = Utils.getDBConnection().Clientes.OrderBy(x => x.NombreEmpresa).Where(x => x.IdFranquicia == franquiciaId)
                        .Select(x => new SelectListItem { Text = x.NombreEmpresa, Value = x.IdCliente.ToString() });
                    return Json(clientes, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json("", JsonRequestBehavior.AllowGet);
                }
            }
            catch
            {
                return Json("", JsonRequestBehavior.AllowGet);
            }
        }

        //
        // GET: /ServicioConsulta/ObtenerSucursales
        public ActionResult ObtenerSucursales(Guid idCliente)
        {
            try
            {
                if (idCliente != null)
                {
                    IEnumerable<SelectListItem> sucursales = Utils.getDBConnection().Sucursals.OrderBy(x => x.NombreSucursal).Where(x => x.IdCliente == idCliente)
                        .Select(x => new SelectListItem { Text = x.NombreSucursal, Value = x.IdSucursal.ToString() });
                    return Json(sucursales, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json("", JsonRequestBehavior.AllowGet);
                }
            }
            catch
            {
                return Json("", JsonRequestBehavior.AllowGet);
            }
        }

        //
        // GET: /ServicioConsulta/ObtenerEquiposSucursal
        public ActionResult ObtenerEquiposSucursal(Guid? idSucursal, int AnioPlanificacion)
        {
            try
            {
                if (idSucursal != null)
                {
                    var equipos = db.Equipos.OrderBy(x => x.Nombre).Where(x => x.IdSucursal == idSucursal && x.Estado.Value == 1)
                        .Select(x => new
                        {
                            nombreEquipo = x.Nombre,
                            codigoEquipo = x.CodigoEquipo,
                            IdEquipo = x.IdEquipo.ToString(),
                            contrato = x.TipoContrato.TipoContrato1,
                            fechasPropuesta = Utils.CalculoMesesPropuesta(x.IdEquipo, getFechaUltimaMantencion(x.IdEquipo), x.FechaInstalacion, x.TipoContrato.Codigo, AnioPlanificacion),
                            fechaInstalacion = Utils.getFechaStrFormat(x.FechaInstalacion, "dd-MM-yyyy"),
                            fechaUltimaMantencion = getFechaUltimaMantecionStr(x.IdEquipo),
                            fechaActual = DateTime.Now.ToString("dd-MM-yyyy")
                        }).ToList();

                    return Json(equipos, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json("", JsonRequestBehavior.AllowGet);
                }
            }
            catch(Exception e)
            {
                return Json("", JsonRequestBehavior.AllowGet);
            }
        }

        //
        // GET: /ServicioConsulta/ObtenerEquiposSucursalDescripcion
        public ActionResult ObtenerEquiposSucursalDescripcion(Guid? idSucursal)
        {
            try
            {
                if (idSucursal != null)
                {
                    var equipos = Utils.getDBConnection().Equipos.OrderBy(x => x.Nombre).Where(x => x.IdSucursal == idSucursal && x.Estado.Value == 1)
                        .Select(x => new
                        {
                            nombreEquipo = x.Nombre,
                            codigoEquipo = x.CodigoEquipo,
                            idEquipo = x.IdEquipo
                        }).ToList();

                    return Json(equipos, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json("", JsonRequestBehavior.AllowGet);
                }
            }
            catch
            {
                return Json("", JsonRequestBehavior.AllowGet);
            }
        }

        //
        // GET: /ServicioConsulta/ObtenerEquiposPlanificacion
        public ActionResult ObtenerEquiposPlanificacion(Guid? idPlanificacion)
        {
            try
            {
                if (idPlanificacion != null)
                {
                    MantencionesDataContext dbTemp = Utils.getDBConnection();
                    Planificacion plan = dbTemp.Planificacions.Where(x => x.IdPlanificacion == idPlanificacion).SingleOrDefault();
                    IEnumerable<Mantencion> mantenciones = dbTemp.Mantencions.Where(x => x.IdPlanificacion == idPlanificacion && x.Habilitado);

                    var equipos = dbTemp.Equipos.OrderBy(x => x.Nombre).Where(x => x.Mantencions.Intersect(mantenciones).Any())
                        .Select(x => new
                        {
                            nombreEquipo = x.Nombre,
                            codigoEquipo = x.CodigoEquipo,
                            idEquipo = x.IdEquipo,
                            tipoContrato = x.TipoContrato.TipoContrato1
                        }).ToList();

                    return Json(equipos, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json("", JsonRequestBehavior.AllowGet);
                }
            }
            catch
            {
                return Json("", JsonRequestBehavior.AllowGet);
            }
        }

        private String getFechaUltimaMantecionStr(Guid idEquipo)
        {
            //Equipo equipo = db.Equipos.Where(x => x.IdEquipo == idEquipo).SingleOrDefault();
            //DateTime? fecha = getFechaUltimaMantencion(idEquipo) ?? equipo.FechaUltimaMantencion;
            DateTime? fecha = getFechaUltimaMantencion(idEquipo);
            String fechaStr = (fecha != null ? fecha.Value.ToString("dd-MM-yyyy") : "N/A");
            return fechaStr;
        }

        private DateTime? getFechaUltimaMantencion(Guid idEquipo) 
        {
            Equipo equipo = db.Equipos.Where(x => x.IdEquipo == idEquipo).SingleOrDefault();
            Mantencion m = db.Mantencions.OrderByDescending(x => x.FechaConfirmacion)
                .Where(x => x.IdEquipo == idEquipo && x.FechaConfirmacion != null && x.Habilitado).FirstOrDefault();
            return (m != null ? m.FechaConfirmacion : (equipo.FechaUltimaMantencion != null ? equipo.FechaUltimaMantencion : null));
        }

        //
        // GET: /ServicioConsulta/ObtenerContactoSucursal
        public ActionResult ObtenerContactoSucursal(Guid? idSucursal)
        {
            try
            {
                if (idSucursal != null)
                {
                    Contacto contacto = Utils.getDBConnection().Contactos.Where(x => x.IdSucursal == idSucursal).FirstOrDefault();
                    return Json(contacto.Correo, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json("", JsonRequestBehavior.AllowGet);
                }
            }
            catch
            {
                return Json("", JsonRequestBehavior.AllowGet);
            }
        }

        //
        // GET: /ServicioConsulta/ObtenerPlanificacionesSucursal
        public ActionResult ObtenerPlanificacionesSucursal(Guid? idSucursal)
        {
            try
            {
                if (idSucursal != null)
                {
                    IEnumerable<Mantencion> mantenciones = db.Mantencions.Where(x => x.Equipo.IdSucursal == idSucursal && x.Habilitado);
                    var planificaciones = db.Planificacions
                        .Where(x => x.Mantencions.Intersect(mantenciones).Any()).Select(x => new
                    {
                        idPlanificacion = x.IdPlanificacion,
                        anio = x.Ano,
                        nombre = x.Nombre,
                    }).ToList();

                    //var planificaciones = db.Planificacions.OrderBy(x => x.Nombre).Where(x => x.ID == idSucursal)
                    //    .Select(x => new
                    //    {
                    //        anio = x.Ano,
                    //        nombre = x.Nombre,
                    //    }).Distinct().ToList();

                    return Json(planificaciones, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json("", JsonRequestBehavior.AllowGet);
                }
            }
            catch
            {
                return Json("", JsonRequestBehavior.AllowGet);
            }
        }
        

        //
        // GET: /ServicioConsulta/ObtenerFormatosCorreo
        public ActionResult ObtenerFormatosCorreo(Guid? idTipoNotificacion)
        {
            try
            {
                var formatos = Utils.getDBConnection().MailTemplates.OrderBy(x => x.Nombre).Where(x => x.IdTipoNotificacion == idTipoNotificacion)
                        .Select(x => new
                {
                    Text = x.Nombre,
                    Value = x.IdMailTemplate
                }).ToList();

                return Json(formatos, JsonRequestBehavior.AllowGet);
                
            }
            catch
            {

MetricArts.JnJ.Mantenciones.Web/Views/Repuestos/CrearNuevo.cshtml
@model MetricArts.JnJ.Mantenciones.Models.Mantenedores.Repuestos.RepuestosViewModel
@{
    ViewBag.Title = "Crear Nuevo Repuesto";
}

<div class="row-fluid">
				<ol class="breadcrumb">
					<li><a href="@Url.Action("Index", "Home")">Inicio</a></li>
					<li><a href="@Url.Action("Index", "Mantenedores")">Mantenedores</a></li>
					<li><a href="@Url.Action("Index", "Repuestos")">Contactos</a></li>
					<li><a href="@Url.Action("CrearNuevo", "Repuestos")">Nuevo</a></li>
				</ol>
			</div>

			<section>
				<div class="row-fluid">
					<h3>Crear Nuevo Repuesto</h3>
				</div>
                @if (TempData["Mensaje"] != null && !String.IsNullOrEmpty(TempData["Mensaje"].ToString()))
                {
                <div class="alert alert-warning alert-dismissible fadeOutMantenedor" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <strong>@(TempData["Mensaje"])</strong>
                </div>
                }
                <br />
                <form action="@Url.Action("CrearNuevo", "Repuestos")" method="POST" class="form-horizontal">
				<div class="row-fluid">
					    
                    <div class="form-group">
							<label class="col-sm-4 control-label">@Html.LabelFor(x => x.FORM.Codigo)</label>
							<div class="col-sm-6">
                                @Html.TextBoxFor(x => x.FORM.Codigo, new { @class = "form-control input-sm" })
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-4 control-label">@Html.LabelFor(x => x.FORM.Categoria)</label>
							<div class="col-sm-6">
                                <select id="categoria" class="form-control input-sm">
                                    <option value="Requerido">Requerido</option>
                                    <option value="Recomendado">Recomendado</option>
                                </select>
                                @Html.HiddenFor(x => x.FORM.Categoria)
							</div>
						</div>
                        
                        <div class="form-group">
							<label class="col-sm-4 control-label">@Html.LabelFor(x => x.FORM.Cantidad)</label>
							<div class="col-sm-6">
                                @Html.TextBoxFor(x => x.FORM.Cantidad, new { @class = "form-control input-sm", @type = "number", @value = "1", @min = "1" })
							</div>
						</div>
                        <div class="form-group">
							<label class="col-sm-4 control-label">@Html.LabelFor(x => x.FORM.Descripcion)</label>
							<div class="col-sm-6">
                                @Html.TextAreaFor(x => x.FORM.Descripcion, new { @class = "form-control", @rows = "3" })
							</div>
						</div>
                        						
				</div>
				<div class="row">
					<div class="col-md-6 col-md-offset-4">
						<button id="crear-repuesto" type="button" class="btn btn-success pull-right">Guardar</button>
                        <a href="@Url.Action("Index", "Repuestos")" class="btn btn-primary">Cancelar</a>
					</div>
                    
				</div>
                </form>
			</section>
@Scripts.Render("~/bundles/custom/mantenedores/repuestos/crear")
<script type="text/javascript">
    $(document).ready(function () {
        init();
    });
</script>

MetricArts.JnJ.Mantenciones.Web/Views/Repuestos/Editar.cshtml
@model MetricArts.JnJ.Mantenciones.Models.Mantenedores.Repuestos.RepuestosViewModel
@{
    ViewBag.Title = "Editar Repuesto";
}

<div class="row-fluid">
				<ol class="breadcrumb">
					<li><a href="@Url.Action("Index", "Home")">Inicio</a></li>
					<li><a href="@Url.Action("Index", "Mantenedores")">Mantenedores</a></li>
					<li><a href="@Url.Action("Index", "Repuestos")">Sucursales</a></li>
					<li>Editar</li>
				</ol>
			</div>

			<section>
                
				<div class="row-fluid">
					<h3>Editar Repuesto</h3>
				</div>
                @if (TempData["Mensaje"] != null && !String.IsNullOrEmpty(TempData["Mensaje"].ToString()))
                {
                <div class="alert alert-warning alert-dismissible fadeOutMantenedor" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <strong>@(TempData["Mensaje"])</strong>
                </div>
                }
                <br />
                <form action="@Url.Action("Editar", "Repuestos")" method="POST" class="form-horizontal">
                    @Html.HiddenFor(x => x.FORM.IdRepuesto)
				<div class="row-fluid">
						<div class="form-group">
							<label class="col-sm-4 control-label">@Html.LabelFor(x => x.FORM.Codigo)</label>
							<div class="col-sm-6">
                                @Html.TextBoxFor(x => x.FORM.Codigo, new { @class = "form-control input-sm" })
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-4 control-label">@Html.LabelFor(x => x.FORM.Categoria)</label>
							<div class="col-sm-6">
                               @* <select id="FORM_IdSucursal" class="form-control input-sm">
                                    <option value="Requerido">Requerido</option>
                                    <option value="Recomendado">Recomendado</option>
                                </select>*@
                                @Html.DropDownListFor(x => x.FORM.Categoria, Model.Categorias, new { @class = "form-control input-sm" })
                                @*@Html.HiddenFor(x => x.FORM.Categoria)*@
							</div>
						</div>
                        
                        <div class="form-group">
							<label class="col-sm-4 control-label">@Html.LabelFor(x => x.FORM.Cantidad)</label>
							<div class="col-sm-6">
                                @Html.TextBoxFor(x => x.FORM.Cantidad, new { @class = "form-control input-sm", @type = "number", @value = "1", @min = "1" })
							</div>
						</div>
                        <div class="form-group">
							<label class="col-sm-4 control-label">@Html.LabelFor(x => x.FORM.Descripcion)</label>
							<div class="col-sm-6">
                                @Html.TextAreaFor(x => x.FORM.Descripcion, new { @class = "form-control", @rows = "3" })
							</div>
						</div>
                        								
				</div>
				<div class="row">
					<div class="col-md-6 col-md-offset-4">
						<input type="submit" class="btn btn-success pull-right" value="Guardar" />
                        <a href="@Url.Action("Index", "Repuestos")" class="btn btn-primary">Cancelar</a>
					</div>
				</div>
                </form>
			</section>
@Scripts.Render("~/bundles/custom/mantenedores/repuestos/editar")
<script type="text/javascript">
    $(document).ready(function () {
        init('@Url.Action("ObtenerClientes", "ServicioConsulta")',
            '@Url.Action("ObtenerSucursalesSinContactos", "ServicioConsulta")');
    });
</script>

MetricArts.JnJ.Mantenciones.Web/Views/Repuestos/Index.cshtml
@model MetricArts.JnJ.Mantenciones.Models.Mantenedores.Repuestos.RepuestosViewModel
@{    
    ViewBag.Title = "Listado Repuestos";
}
<section class="container-fluid">
    <article>
        <div class="row">
		    <ol class="breadcrumb">
			    <li><a href="@Url.Action("Index", "Home")">Inicio</a></li>
			    <li><a href="@Url.Action("Index", "Mantenedores")">Mantenedores</a></li>
				<li><a href="@Url.Action("Index", "Repuestos")">Repuestos</a></li>
			</ol>
		</div>

        <article>
		    <div class="bs-callout bs-callout-JJ">
                <legend>Repuestos</legend>
                <a href="@Url.Action("CrearNuevo", "Repuestos")" data-toggle="confirmation"  title="Nuevo Repuesto" class="btn btn-success">
                    <span class='glyphicon glyphicon-plus-sign'></span> Crear Nuevo
                </a>

                <button class="btn btn-primary" type="button">
			        Cantidad Total <span class="badge">@Model.Repuestos.Count()</span>
				</button>
		    </div>
		</article>

        <br />
        @if (TempData["Mensaje"] != null && !String.IsNullOrEmpty(TempData["Mensaje"].ToString()))
        {
            <div class="alert alert-success alert-dismissible fadeOutMantenedor" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <strong>@(TempData["Mensaje"])</strong>
            </div>
        }
        <br />
        <div class="row">
            <div class="table-responsive">                            
                <table id="listado-mantenedor" class="table table-striped table-condensed display">
                    <thead>
                        <tr>
                            <th>@Html.DisplayName("Código")</th>
                            <th>@Html.DisplayName("Descripción")</th>
                            <th>@Html.DisplayName("Categoría")</th>
                            <th>@Html.DisplayName("Cantidad")</th>
                            <th>Editar</th>
                            <th>Eliminar</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Repuestos)
                        {
                            <tr>
                                <td>@Html.DisplayFor(modelItem => item.Codigo)</td>
                                <td>@Html.DisplayFor(modelItem => item.Descripcion)</td>
                                <td><strong>@Html.DisplayFor(modelItem => item.Categoria)</strong></td>
                                <td>@Html.DisplayFor(modelItem => item.Cantidad)</td>
                                <td><a href="@Url.Action("Editar", "Repuestos", new { IdRepuesto = item.IdRepuesto })" class="btn btn-default"><span class='glyphicon glyphicon-edit'></span></a></td>
                                <td>
                                     <a href="@Url.Action("Eliminar", "Repuestos", new { IdRepuesto = item.IdRepuesto })" class="btn btn-default" onclick="if(!confirm('Está a punto de eliminar este repuesto.\n¿Desea continuar?.')) return false;"><span class='glyphicon glyphicon-trash'></span></a> 
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
			</div>
		</div>
    </article>
</section>
@Scripts.Render("~/bundles/custom/mantenedores/repuestos/listado")
<script type="text/javascript">
    $(document).ready(function () {
        init();
    });
</script>