MetricArts.JnJ.Mantenciones.Web/Models/Mantenciones/AgendarMantencionesFormModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MetricArts.JnJ.Mantenciones.Models.Mantenciones
{
    public class AgendarMantencionesFormModel
    {
        public Guid IdPlanificacionIn { get; set; }
        public Guid IdMensajeStageIn { get; set; }
        public Guid IdEquipoIn { get; set; }
        public String[] fechasSelectedIn { get; set; }
    }
}

MetricArts.JnJ.Mantenciones.Web/Models/Mantenciones/ClientsFormModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MetricArts.JnJ.Mantenciones.Models.Mantenciones
{
    public class ClientsFormModel
    {

    }
}

MetricArts.JnJ.Mantenciones.Web/Models/Mantenciones/CrearMantencionFormModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace MetricArts.JnJ.Mantenciones.Models.Mantenciones
{
    public class CrearMantencionFormModel
    {
        [DisplayName("Nombre Planificación")]
        public string Nombre { get; set; }

        [DisplayName("Tipo Contrato")]
        public Guid IdTipoContrato { get; set; }

        [StringLength(1023)]
        [DisplayName("Descripción")]
        public string Descripcion { get; set; }
    }
}

MetricArts.JnJ.Mantenciones.Web/Controllers/GestionMantenciones/Mantenciones/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MetricArts.JnJ.Mantenciones.Models.Mantenciones;
using MetricArts.JnJ.Mantenciones.Helpers;
using MetricArts.JnJ.Mantenciones.Core;

namespace MetricArts.JnJ.Mantenciones.Controllers.GestionMantenciones.Mantenciones
{
    public class ClientsController : Controller
    {
        //
        // GET: /Clients/DescargaPDF?ID=
        public ActionResult DescargaPDF(Guid ID)
        {
            MensajeStage msg = Utils.getDBConnection().MensajeStages.Where(x => x.IdMensajeStage == ID).SingleOrDefault();
            string html = msg.CuerpoHTMLPDF;
            byte[] buffer = Utils.createPDF(html);
            return File(buffer, "application/pdf", msg.Planificacion.Nombre + "-" + msg.Planificacion.Ano + "_" + DateTime.Now.ToShortDateString() + ".pdf");
        }

        //
        // GET: /Clients/Checklist?ID=
        public ActionResult Checklist(Guid ID)
        {
            return View();
        }

        //
        // GET: /Clients/EncuestaSatisfaccion?ID=
        public ActionResult EncuestaSatisfaccion(Guid ID)
        {
            return View();
        }

        //
        // GET: /Clients/AgendarMantenciones?ID=
        [HttpGet]
        public ActionResult AgendarMantenciones(String ID)
        {
            AgendarMantencionesViewModel model = new AgendarMantencionesViewModel(ID);
            return View(model);
        }

        //
        // POST: /Clients/AgendarMantenciones?ID=
        [HttpPost]
        public ActionResult AgendarMantenciones(Guid IdPlanificacion, Guid IdMensajeStage, Guid IdEquipo, String[] fechasSelected)
        {
            AgendarMantencionesFormModel FORM = new AgendarMantencionesFormModel();
            FORM.IdPlanificacionIn = IdPlanificacion;
            FORM.IdMensajeStageIn = IdMensajeStage;
            FORM.IdEquipoIn = IdEquipo;
            FORM.fechasSelectedIn = fechasSelected;
            AgendarMantencionesViewModel model = new AgendarMantencionesViewModel(FORM);
            model.persist();
            return View(model);
        }

        //
        // GET: /Clients/ObtenerFeriados
        [HttpGet]
        public ActionResult ObtenerFeriados(Guid IdPlanificacion)
        {
            try
            {
                Planificacion pl = Utils.getDBConnection().Planificacions.Single(x => x.IdPlanificacion == IdPlanificacion);
                CalendarioFeriadosPai c = Utils.getDBConnection().CalendarioFeriadosPais.Single(x => x.Anio == pl.Ano);
                Pais p = Utils.getDBConnection().Pais.Single(x => x.Nombre == "Chile");

                    if(c != null) {
                        var fechas = Utils.getDBConnection().CalendarioFeriadosFechas.Where(x => x.IdCalendarioFeriadosPais == c.IdCalendarioFeriadosPais && x.CalendarioFeriadosPai.Pais == p)
                        .Select(x => new
                        {
                            fecha = x.Fecha.ToShortDateString()
                        }).ToList();

                        return Json(fechas, JsonRequestBehavior.AllowGet);
                    }
                    else {
                        return Json("", JsonRequestBehavior.AllowGet);
                    }        
            }
            catch (Exception e)
            {
                return Json("", JsonRequestBehavior.AllowGet);
            }
        }

        //
        // GET: /Clients/ObtenerDisponibilidadIngeniero
        [HttpGet]
        public ActionResult ObtenerDisponibilidadIngeniero(Guid IdPlanificacion)
        {
            try
            {
                Planificacion pl = Utils.getDBConnection().Planificacions.Single(x => x.IdPlanificacion == IdPlanificacion);
                List<Ingeniero> ings = pl.Mantencions.Where(x => x.Planificacion == pl && x.Habilitado).Select(x => x.Equipo.Ingeniero).ToList();

                List<string> fechas = new List<string>();
                List<string> fechasAux;

                foreach(Ingeniero i in ings) {
                    fechasAux = i.Mantencions.Where(x => x.FechaConfirmacion != null).Select(x => x.FechaConfirmacion.Value.ToShortDateString()).ToList();
                    fechas.AddRange(fechasAux);
                }

                return Json(fechas, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return Json("", JsonRequestBehavior.AllowGet);
            }
        }
    }
}

MetricArts.JnJ.Mantenciones.Web/Controllers/GestionMantenciones/Mantenciones/MantencionesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MetricArts.JnJ.Mantenciones.Models.Mantenciones;
using MetricArts.JnJ.Mantenciones.Models.Notificaciones;
using MetricArts.JnJ.Mantenciones.Core;
using MetricArts.JnJ.Mantenciones.Helpers;
using System.Globalization;

namespace MetricArts.JnJ.Mantenciones.Controllers.GestionMantenciones.Mantenciones
{
    [Authorize]
    public class MantencionesController : Controller
    {
        //
        // GET: /Mantenciones/

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult CrearMantencionManual() {
            CrearMantencionViewModel model = new CrearMantencionViewModel();
            return View(model);
        }

        [HttpGet]
        public ActionResult Seguimiento()
        {
            SeguimientoViewModel model = new SeguimientoViewModel(DateTime.Now.Year, DateTime.Now.ToString("dd-MM-yyyy"));
            return View(model);
        }

        [HttpPost]
        public ActionResult Seguimiento(SeguimientoFormModel FORM)
        {
            SeguimientoViewModel model = new SeguimientoViewModel(FORM);
            return View(model);
        }

        //
        // POST: /Mantenciones/CambiarEstadoMantencion
        [HttpPost]
        public ActionResult CambiarEstadoMantencion(Guid? IdMantencion, int? nuevoEstado, int? anio, string fecha, string obs)
        {
            SeguimientoFormModel FORM = new SeguimientoFormModel();
            FORM.IdMantencion = IdMantencion.Value;
            FORM.nuevoEstado = nuevoEstado.Value;
            FORM.anioPlanificacion = anio;
            FORM.fechaSelected = fecha;
            FORM.userName = User.Identity.Name;
            FORM.observaciones = obs;
            SeguimientoViewModel model = new SeguimientoViewModel(FORM);
            model.peristNuevoEstado();
            return null;
        }

        public ActionResult ObtenerMantencionesPorFecha(string FechaSeleccionada, int tipoMantencion)
        {
            try
            {
                if (FechaSeleccionada != null)
                {
                    MantencionesDataContext dbTemp = Utils.getDBConnection();
                    DateTime fechaSelected = DateTime.ParseExact(FechaSeleccionada, "dd-MM-yyyy", CultureInfo.InvariantCulture);
                    var estadosValidos = (tipoMantencion == 1 ? new[] { 3, 4, 5 } : new[] { 2 });
                    var mantenciones = dbTemp.Mantencions.OrderByDescending(x => x.FechaIngreso)
                                                            .Where(x => x.FechaConfirmacion == fechaSelected && estadosValidos.Contains(x.EstadoMantencion.Codigo) && x.Habilitado)
                                                            .Select(x => new
                                                            {
                                                                Equipo = x.Equipo.Nombre,
                                                                Codigo = x.Equipo.CodigoEquipo,
                                                                Anio = x.Planificacion.Ano,
                                                                Cliente = x.Equipo.Sucursal.Cliente.NombreEmpresa,
                                                                Sucursal = x.Equipo.Sucursal.NombreSucursal,
                                                                Ingeniero = x.Ingeniero.Usuario.Nombre + " " + x.Ingeniero.Usuario.ApellidoPaterno,
                                                                IdIngeniero = x.IdIngeniero,
                                                                ID = x.IdMantencion,
                                                                EstadoCodigo = x.EstadoMantencion.Codigo,
                                                                Checklist = (x.CuestionarioMantencions.Where(y => y.IdMantencion == x.IdMantencion && y.Cuestionario.TipoCuestionario.Codigo == 1).SingleOrDefault() != null ? x.CuestionarioMantencions.Where(y => y.IdMantencion == x.IdMantencion && y.Cuestionario.TipoCuestionario.Codigo == 1).SingleOrDefault().Cuestionario.Descripcion : "<i>No Asignado</i>"),
                                                                ChecklistRespondido = (x.CuestionarioMantencions.Where(y => y.IdMantencion == x.IdMantencion && y.Cuestionario.TipoCuestionario.Codigo == 1).SingleOrDefault() != null ? x.CuestionarioMantencions.Where(y => y.IdMantencion == x.IdMantencion && y.Cuestionario.TipoCuestionario.Codigo == 1).SingleOrDefault().Respondida : false )
                                                            }).ToList();

                    return Json(mantenciones, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json("", JsonRequestBehavior.AllowGet);
                }
            }
            catch(Exception e)
            {
                return Json("", JsonRequestBehavior.AllowGet);
            }
        }


        [HttpGet]
        public ActionResult CalendarioJsonFeed(int tipoMantencion)
        {
            try
            {
                var estadosValidos = (tipoMantencion == 1 ? new[] { 3, 4, 5 } : new[] { 2 });
                var coloresEventos = new[] { "#F89406", "#0088CC", "#BD362F", "#51A351" };

                IQueryable<Mantencion> mantenciones = Utils.getDBConnection().Mantencions.Where(x => x.FechaConfirmacion.HasValue && estadosValidos.Contains(x.EstadoMantencion.Codigo) && x.Habilitado);
                var eventos = mantenciones
                    .Select(x => new
                    {
                        start = x.FechaConfirmacion.ToString(),
                        title = x.Equipo.Sucursal.Cliente.NombreEmpresa + " - " + x.Equipo.Sucursal.NombreSucursal + " - " + x.Equipo.Nombre,
                        id = x.IdMantencion.ToString(),
                        color = coloresEventos.GetValue(x.EstadoMantencion.Codigo - 2), 
                        tipoContrato = x.TipoContrato.TipoContrato1,
                        estadoMantencion = x.EstadoMantencion.Estado,
                        sucursal = x.Equipo.Sucursal.NombreSucursal,
                        cliente = x.Equipo.Sucursal.Cliente.NombreEmpresa,
                        ingeniero = x.Ingeniero.Usuario.Nombre + " " + x.Ingeniero.Usuario.ApellidoPaterno,
                        codigoEquipo = x.Equipo.CodigoEquipo
                    }).ToList();

                return Json(eventos, JsonRequestBehavior.AllowGet);
            }
            catch
            {
                return Json("", JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult VigentesReasignacionIngeniero(Guid IdIngeniero, Guid IdMantencion)
        {
            VigentesReasignacionIngenieroViewModel model = new VigentesReasignacionIngenieroViewModel(IdIngeniero, IdMantencion);
            return Json(model.persistChanges());
        }

        [HttpPost]
        public ActionResult VigentesReasignacionFecha(string fechaSelected, Guid IdMantencion)
        {
            VigentesReasignacionFechaViewModel model = new VigentesReasignacionFechaViewModel(fechaSelected, IdMantencion);
            return Json(model.persistChanges());
        }

        [HttpPost]
        public ActionResult VigentesAsignacionChecklist(Guid IdCuestionario, Guid IdMantencion)
        {
            VigentesAsignacionChecklistViewModel model = new VigentesAsignacionChecklistViewModel(IdCuestionario, IdMantencion);
            return Json(model.persistChanges());
        }

        [HttpGet]
        public ActionResult Repuestos()
        {
            RepuestosViewModel model = new RepuestosViewModel(User.Identity.Name);
            return View(model);
        }

        public ActionResult PlantillaCorreoRepuestosPreview(Guid IdMailTemplate, Guid IdDistribuidor, Guid IdSolicitudKitRepuesto)
        {
            var uri = new Uri(Request.Url.AbsoluteUri);
            string CurrentURL = uri.GetLeftPart(UriPartial.Authority);
            RepuestosFormModel FORM = new RepuestosFormModel();
            FORM.userName = User.Identity.Name;
            FORM.IdSolicitudKitRepuestos = IdSolicitudKitRepuesto;
            FORM.IdDistribuidor = IdDistribuidor;
            FORM.IdMailTemplate = IdMailTemplate;
            RepuestosViewModel model = new RepuestosViewModel(FORM);
            model.setMailTemplate();
            return PartialView(model);
        }

        [HttpPost]
        public ActionResult EnviarSolicitudRepuestos(Guid IdMailTemplate, Guid IdDistribuidor, Guid IdSolicitudKitRepuesto, string contactosPara, string contactosCC, string contactosBCC)
        {
            var uri = new Uri(Request.Url.AbsoluteUri);
            string CurrentURL = uri.GetLeftPart(UriPartial.Authority);

            RepuestosFormModel FORM = new RepuestosFormModel();
            FORM.userName = User.Identity.Name;
            FORM.IdMailTemplate = IdMailTemplate;
            FORM.IdDistribuidor = IdDistribuidor;
            FORM.IdSolicitudKitRepuestos = IdSolicitudKitRepuesto;

            FORM.contactoPara = contactosPara;
            FORM.contactosCC = contactosCC;
            FORM.contactosBCC = contactosBCC;
            FORM.urlPrefix = CurrentURL;

            RepuestosViewModel model = new RepuestosViewModel(FORM);
            return Json(model.persistChanges());
        }

        [HttpPost]
        public ActionResult InactivarMantencion(Guid IdMantencion)
        {
            InactivarMantencionViewModel model = new InactivarMantencionViewModel(IdMantencion);
            return Json(model.persistChanges());
        }

        [HttpPost]
        public ActionResult HabilitarMantencion(Guid IdMantencion)
        {
            InactivarMantencionViewModel model = new InactivarMantencionViewModel(IdMantencion);
            return Json(model.persistChangesHabilitar());

MetricArts.JnJ.Mantenciones.Web/Controllers/GestionMantenciones/Mantenciones/ProviderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MetricArts.JnJ.Mantenciones.Models.Mantenciones;

namespace MetricArts.JnJ.Mantenciones.Controllers.GestionMantenciones.Mantenciones
{
    public class ProviderController : Controller
    {
        //
        // GET: /Provider/

        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /Provider/ConfirmarReciboMail?ID

        public ActionResult ConfirmarReciboMail(String ID)
        {
            new ProviderViewModel(ID);
            return View();
        }
    }
}

MetricArts.JnJ.Mantenciones.Web/Controllers/Reportes/ReportesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MetricArts.JnJ.Mantenciones.Controllers.Reportes
{
    public class ReportesController : Controller
    {
        //
        // GET: /Reportes/
        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /Reportes/Correos
        public ActionResult Correos()
        {
            return View();
        }

        //
        // GET: /Reportes/Mantenciones
        public ActionResult Mantenciones()
        {
            return View();
        }
    }
}

MetricArts.JnJ.Mantenciones.Web/Views/Reportes/Correos.cshtml
@{
    ViewBag.Title = "Correos";
}

<section>
				<div class="row-fluid">
					<ol class="breadcrumb">
						<li><a href="Index.html">Inicio</a></li>
						<li><a href="Reportes.html">Reportes</a></li>
						<li><a href="ReportesCorreos.html">Correos</a></li>
					</ol>
				</div>
				<article>
					<div class="row-fluid">
						<h3>Reporte de Correos</h3>
						<ul class="nav nav-tabs" role="tablist">
							<li role="tab" class="active"><a href="#Lista" aria-controls="Lista" role="tab" data-toggle="tab">Lista</a></li>
							<li role="tab"><a href="#Grafico" aria-controls="Grafico" role="Gráfico" data-toggle="tab">Gráfico</a></li>
						</ul>
					</div>
					<div class="tab-content">
						<div role="tab" class="tab-pane active" id="Lista">
							<div class="row-fluid">
								<div class="bs-callout bs-callout-JJ">
									<legend>Filtros</legend>
									<form class="form-horizontal">
										<div class="row">
											<div class="col-md-6">
												<div class="form-group">
													<label class="col-sm-4 control-label">Desde</label>
													<div class="col-sm-7">

														<div class="input-group">
															<input type="text" class="form-control datepickershow" disabled="disabled"/>
															<span class="input-group-btn">
																<button class="btn btn-default dateButton" type="button">
																	<span class="glyphicon glyphicon-calendar"></span>
																</button>
															</span>
														</div>
													</div>
												</div>
											</div>
											<div class="col-md-6">
												<div class="form-group">
													<label class="col-sm-4 control-label">Hasta</label>
													<div class="col-sm-7">
														<div class="input-group">
															<input type="text" class="form-control datepickershow" disabled="disabled"/>
															<span class="input-group-btn">
																<button class="btn btn-default dateButton" type="button">
																	<span class="glyphicon glyphicon-calendar"></span>
																</button>
															</span>
														</div>
													</div>
												</div>
											</div>
										</div>
										<div class="row">
											<div class="col-md-6">
												<div class="form-group">
													<label class="col-sm-4 control-label">Tipo de Estados</label>
													<div class="col-sm-7">
														<select class="form-control input-sm">
															<option>Opción</option>
															<option>Opción</option>
															<option>Opción</option>
														</select>
													</div>
												</div>
											</div>
											<div class="col-md-6">
												<div class="form-group">
													<div class="col-md-7 col-md-offset-4">
														<button type="button" class="btn btn-JJ pull-right">
															Filtrar
														</button>
													</div>
												</div>	
											</div>
										</div>
									</form>
								</div>
							</div>
							</br>
							<div class="row-fluid">
								<div class="table-responsive">
									<table class="table table-striped table-condensed">
										<thead>
											<tr>
												<th>Cliente</th>
												<th>Sucursal</th>
												<th>Ingeniero</th>
												<th>Fecha</th>
												<th>Estado</th>
											</tr>
										</thead>
										<tbody>
											<tr>
												<th>Clínica Tabancura (Central)</th>
												<td>VITROS ECI (3354)</td>
												<td>Sergio Rojas</td>
												<td>01-01-2014</td>
												<td>Asignar dia para Mantención</td>
											</tr>
											<tr>
												<th>Laboratorios Clínicos Bionet (Hospital Clínico Universidad Mayor - Temuco)</th>
												<td>VITROS 250</td>
												<td>Cristian MacDonald</td>
												<td>13-01-2014</td>
												<td>Confirmado por Cliente</td>
											</tr>
											<tr>
												<th>Clínica Dávila (Banco de Sangre)</th>
												<td>AUTOVUE INNOVA (1585)</td>
												<td>Alamiro Campos</td>
												<td>15-01-2014</td>
												<td>Confirmado por Cliente</td>
											</tr>
										</tbody>
									</table>
								</div>
							</div>
						</div>
						<div role="tab" class="tab-pane active" id="Grafico">
							<div class="row-fluid">
								<div id="MonthPag"></div>
							</div>
							<div class="row-fluid">
								<div class="bs-panel">
									<canvas id="chart1"/>
								</div>
							</div>
						</div>
					</div>
				</article>
			</section>

MetricArts.JnJ.Mantenciones.Web/Views/Reportes/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<section>
				<div class="row-fluid">
					<ol class="breadcrumb">
						<li><a href="@Url.Action("Index", "Reportes")">Inicio</a></li>
						<li><a href="Reportes.html">Reportes</a></li>
					</ol>
				</div>
				<div class="row-fluid">
					<button dir="@Url.Action("Mantenciones", "Reportes")" data-toggle="tooltip" data-placement="bottom" title="Estado de Mantenciones" class="shortcut-button"> 
						<span class="glyphicon glyphicon-briefcase"></span>
						<span class="title">Mantenciones</span>
					</button>
					<button dir="@Url.Action("Correos", "Reportes")" data-toggle="tooltip" data-placement="bottom" title="Estado de Correos" class="shortcut-button">
						<span class="glyphicon glyphicon-envelope"></span>
						<span class="title">Correos</span>
					</button>
				</div>
			</section>