MetricArts.JnJ.Mantenciones.Web/Models/Mantenedores/KitRepuestos/KitRepuestosFormModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;

namespace MetricArts.JnJ.Mantenciones.Models.Mantenedores.KitRepuestos
{
    public class KitRepuestosFormModel
    {
        [DisplayName("Nombre")]
        public string Nombre { get; set; }

        [DisplayName("Franquicia")]
        public Guid IdFranquicia { get; set; }

        [DisplayName("Cliente")]
        public Guid IdCliente { get; set; }

        [DisplayName("Sucursal")]
        public Guid IdSucursal { get; set; }

        public Guid IdEquipo { get; set; }

        public Guid IdKitRepuesto { get; set; }

        public string RepuestosIds { get; set; }

        public string userName { get; set; }
    }
}

MetricArts.JnJ.Mantenciones.Web/Controllers/Mantenedores/KitRepuestosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MetricArts.JnJ.Mantenciones.Models.Mantenedores.KitRepuestos;
using MetricArts.JnJ.Mantenciones.Helpers;

namespace MetricArts.JnJ.Mantenciones.Controllers.Mantenedores
{
    public class KitRepuestosController : Controller
    {
        //
        // GET: /KitRepuestos/

        public ActionResult Index()
        {
            KitRepuestosViewModel model = new KitRepuestosViewModel();
            return View(model);
        }

        //
        // GET: /KitRepuestos/CrearNuevo
        [HttpGet]
        public ActionResult CrearNuevo()
        {
            KitRepuestosViewModel model = new KitRepuestosViewModel(User.Identity.Name);
            return View(model);
        }

        //
        // POST: /KitRepuestos/CrearNuevo
        [HttpPost]
        public ActionResult CrearNuevo(KitRepuestosFormModel form)
        {
            KitRepuestosViewModel model = new KitRepuestosViewModel(form);

            try
            {
                if (ModelState.IsValid)
                {
                    form.userName = User.Identity.Name;
                    model.create();
                    Mensaje = "Se ha creado el KIT con éxito.";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception e)
            {
                model = new KitRepuestosViewModel(User.Identity.Name);
                Mensaje = "No se han podido guardar los cambios. Intente nuevamente. Si el problema persiste, favor contactarse con servicio técnico.";
            }
            return View(model);
        }

        //
        // GET: /KitRepuestos/Editar
        [HttpGet]
        public ActionResult Editar(Guid IdKitRepuesto)
        {
            KitRepuestosViewModel model = new KitRepuestosViewModel(IdKitRepuesto);
            return View(model);
        }

        //
        // POST: /KitRepuestos/Editar
        [HttpPost]
        public ActionResult Editar(KitRepuestosFormModel form)
        {
            KitRepuestosViewModel model = new KitRepuestosViewModel(form);

            try
            {
                if (ModelState.IsValid)
                {
                    form.userName = User.Identity.Name;
                    model.update();
                    Mensaje = "Se han guardado los cambios con éxito.";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception e)
            {
                model = new KitRepuestosViewModel(form.IdKitRepuesto);
                Mensaje = "No se han podido guardar los cambios. Intente nuevamente. Si el problema persiste, favor contactarse con servicio técnico.";
            }
            return View(model);
        }

        //
        // GET: /KitRepuestos/Eliminar
        [HttpGet]
        public ActionResult Eliminar(Guid IdKitRepuesto)
        {
            KitRepuestosViewModel model = new KitRepuestosViewModel(IdKitRepuesto);
            model.delete();
            Mensaje = "Se ha eliminado el KIT con éxito.";
            return RedirectToAction("Index");
        }

        //
        // GET: /KitRepuestos/AsociarRepuestos
        [HttpGet]
        public ActionResult AsociarRepuestos(Guid IdKitRepuesto)
        {
            KitRepuestosViewModel model = new KitRepuestosViewModel(IdKitRepuesto);
            return View(model);
        }

        //
        // POST: /KitRepuestos/AsociarRepuestos
        [HttpPost]
        public ActionResult AsociarRepuestos(KitRepuestosFormModel form)
        {
            KitRepuestosViewModel model = new KitRepuestosViewModel(form);

            try
            {
                if (ModelState.IsValid)
                {
                    form.userName = User.Identity.Name;
                    model.addRepuestos();
                    Mensaje = "Se han asociado los repuestos con éxito.";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception e)
            {
                model = new KitRepuestosViewModel(form.IdKitRepuesto);
                Mensaje = "No se han podido guardar los cambios. Intente nuevamente. Si el problema persiste, favor contactarse con servicio técnico.";
            }
            return View(model);
        }

        public string Mensaje
        {
            set
            {
                TempData["Mensaje"] = value;
            }
        }

        //
        // GET: /KitRepuestos/GetKitRepuestosRepuestos?IdKitRepuesto
        [HttpGet]
        public ActionResult GetKitRepuestosRepuestos(Guid IdKitRepuesto)
        {
            try
            {
                var kitRepuestoRepuestos = Utils.getDBConnection().KitRepuestoRepuestos.OrderBy(x => x.Repuesto.Codigo).Where(x => x.IdKitRepuesto == IdKitRepuesto).Select(x => new
                {
                    Codigo = x.Repuesto.Codigo,
                    Categoria = x.Repuesto.Categoria,
                    Cantidad = x.Repuesto.Cantidad,
                    Descripcion = x.Repuesto.Descripcion
                }).ToList();

                return Json(kitRepuestoRepuestos, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return Json("", JsonRequestBehavior.AllowGet);
            }
        }
    }
}

MetricArts.JnJ.Mantenciones.Web/Controllers/ServicioConsultaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MetricArts.JnJ.Mantenciones.Core;
using MetricArts.JnJ.Mantenciones.Helpers;

namespace MetricArts.JnJ.Mantenciones.Controllers
{
    public class ServicioConsultaController : Controller
    {
        protected MantencionesDataContext db = new MantencionesDataContext()
                .WithConnectionStringFromConfiguration();

        //
        // GET: /ServicioConsulta/ObtenerClientes
        public ActionResult ObtenerClientes(Guid franquiciaId)
        {
            try
            {
                if (franquiciaId != null)
                {
                    IEnumerable<SelectListItem> clientes = Utils.getDBConnection().Clientes.OrderBy(x => x.NombreEmpresa).Where(x => x.IdFranquicia == franquiciaId)
                        .Select(x => new SelectListItem { Text = x.NombreEmpresa, Value = x.IdCliente.ToString() });
                    return Json(clientes, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json("", JsonRequestBehavior.AllowGet);
                }
            }
            catch
            {
                return Json("", JsonRequestBehavior.AllowGet);
            }
        }

        //
        // GET: /ServicioConsulta/ObtenerSucursales
        public ActionResult ObtenerSucursales(Guid idCliente)
        {
            try
            {
                if (idCliente != null)
                {
                    IEnumerable<SelectListItem> sucursales = Utils.getDBConnection().Sucursals.OrderBy(x => x.NombreSucursal).Where(x => x.IdCliente == idCliente)
                        .Select(x => new SelectListItem { Text = x.NombreSucursal, Value = x.IdSucursal.ToString() });
                    return Json(sucursales, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json("", JsonRequestBehavior.AllowGet);
                }
            }
            catch
            {
                return Json("", JsonRequestBehavior.AllowGet);
            }
        }

        //
        // GET: /ServicioConsulta/ObtenerEquiposSucursal
        public ActionResult ObtenerEquiposSucursal(Guid? idSucursal, int AnioPlanificacion)
        {
            try
            {
                if (idSucursal != null)
                {
                    var equipos = db.Equipos.OrderBy(x => x.Nombre).Where(x => x.IdSucursal == idSucursal && x.Estado.Value == 1)
                        .Select(x => new
                        {
                            nombreEquipo = x.Nombre,
                            codigoEquipo = x.CodigoEquipo,
                            IdEquipo = x.IdEquipo.ToString(),
                            contrato = x.TipoContrato.TipoContrato1,
                            fechasPropuesta = Utils.CalculoMesesPropuesta(x.IdEquipo, getFechaUltimaMantencion(x.IdEquipo), x.FechaInstalacion, x.TipoContrato.Codigo, AnioPlanificacion),
                            fechaInstalacion = Utils.getFechaStrFormat(x.FechaInstalacion, "dd-MM-yyyy"),
                            fechaUltimaMantencion = getFechaUltimaMantecionStr(x.IdEquipo),
                            fechaActual = DateTime.Now.ToString("dd-MM-yyyy")
                        }).ToList();

                    return Json(equipos, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json("", JsonRequestBehavior.AllowGet);
                }
            }
            catch(Exception e)
            {
                return Json("", JsonRequestBehavior.AllowGet);
            }
        }

        //
        // GET: /ServicioConsulta/ObtenerEquiposSucursalDescripcion
        public ActionResult ObtenerEquiposSucursalDescripcion(Guid? idSucursal)
        {
            try
            {
                if (idSucursal != null)
                {
                    var equipos = Utils.getDBConnection().Equipos.OrderBy(x => x.Nombre).Where(x => x.IdSucursal == idSucursal && x.Estado.Value == 1)
                        .Select(x => new
                        {
                            nombreEquipo = x.Nombre,
                            codigoEquipo = x.CodigoEquipo,
                            idEquipo = x.IdEquipo
                        }).ToList();

                    return Json(equipos, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json("", JsonRequestBehavior.AllowGet);
                }
            }
            catch
            {
                return Json("", JsonRequestBehavior.AllowGet);
            }
        }

        //
        // GET: /ServicioConsulta/ObtenerEquiposPlanificacion
        public ActionResult ObtenerEquiposPlanificacion(Guid? idPlanificacion)
        {
            try
            {
                if (idPlanificacion != null)
                {
                    MantencionesDataContext dbTemp = Utils.getDBConnection();
                    Planificacion plan = dbTemp.Planificacions.Where(x => x.IdPlanificacion == idPlanificacion).SingleOrDefault();
                    IEnumerable<Mantencion> mantenciones = dbTemp.Mantencions.Where(x => x.IdPlanificacion == idPlanificacion && x.Habilitado);

                    var equipos = dbTemp.Equipos.OrderBy(x => x.Nombre).Where(x => x.Mantencions.Intersect(mantenciones).Any())
                        .Select(x => new
                        {
                            nombreEquipo = x.Nombre,
                            codigoEquipo = x.CodigoEquipo,
                            idEquipo = x.IdEquipo,
                            tipoContrato = x.TipoContrato.TipoContrato1
                        }).ToList();

                    return Json(equipos, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json("", JsonRequestBehavior.AllowGet);
                }
            }
            catch
            {
                return Json("", JsonRequestBehavior.AllowGet);
            }
        }

        private String getFechaUltimaMantecionStr(Guid idEquipo)
        {
            //Equipo equipo = db.Equipos.Where(x => x.IdEquipo == idEquipo).SingleOrDefault();
            //DateTime? fecha = getFechaUltimaMantencion(idEquipo) ?? equipo.FechaUltimaMantencion;
            DateTime? fecha = getFechaUltimaMantencion(idEquipo);
            String fechaStr = (fecha != null ? fecha.Value.ToString("dd-MM-yyyy") : "N/A");
            return fechaStr;
        }

        private DateTime? getFechaUltimaMantencion(Guid idEquipo) 
        {
            Equipo equipo = db.Equipos.Where(x => x.IdEquipo == idEquipo).SingleOrDefault();
            Mantencion m = db.Mantencions.OrderByDescending(x => x.FechaConfirmacion)
                .Where(x => x.IdEquipo == idEquipo && x.FechaConfirmacion != null && x.Habilitado).FirstOrDefault();
            return (m != null ? m.FechaConfirmacion : (equipo.FechaUltimaMantencion != null ? equipo.FechaUltimaMantencion : null));
        }

        //
        // GET: /ServicioConsulta/ObtenerContactoSucursal
        public ActionResult ObtenerContactoSucursal(Guid? idSucursal)
        {
            try
            {
                if (idSucursal != null)
                {
                    Contacto contacto = Utils.getDBConnection().Contactos.Where(x => x.IdSucursal == idSucursal).FirstOrDefault();
                    return Json(contacto.Correo, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json("", JsonRequestBehavior.AllowGet);
                }
            }
            catch
            {
                return Json("", JsonRequestBehavior.AllowGet);
            }
        }

        //
        // GET: /ServicioConsulta/ObtenerPlanificacionesSucursal
        public ActionResult ObtenerPlanificacionesSucursal(Guid? idSucursal)
        {
            try
            {
                if (idSucursal != null)
                {
                    IEnumerable<Mantencion> mantenciones = db.Mantencions.Where(x => x.Equipo.IdSucursal == idSucursal && x.Habilitado);
                    var planificaciones = db.Planificacions
                        .Where(x => x.Mantencions.Intersect(mantenciones).Any()).Select(x => new
                    {
                        idPlanificacion = x.IdPlanificacion,
                        anio = x.Ano,
                        nombre = x.Nombre,
                    }).ToList();

                    //var planificaciones = db.Planificacions.OrderBy(x => x.Nombre).Where(x => x.ID == idSucursal)
                    //    .Select(x => new
                    //    {
                    //        anio = x.Ano,
                    //        nombre = x.Nombre,
                    //    }).Distinct().ToList();

                    return Json(planificaciones, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json("", JsonRequestBehavior.AllowGet);
                }
            }
            catch
            {
                return Json("", JsonRequestBehavior.AllowGet);
            }
        }
        

        //
        // GET: /ServicioConsulta/ObtenerFormatosCorreo
        public ActionResult ObtenerFormatosCorreo(Guid? idTipoNotificacion)
        {
            try
            {
                var formatos = Utils.getDBConnection().MailTemplates.OrderBy(x => x.Nombre).Where(x => x.IdTipoNotificacion == idTipoNotificacion)
                        .Select(x => new
                {
                    Text = x.Nombre,
                    Value = x.IdMailTemplate
                }).ToList();

                return Json(formatos, JsonRequestBehavior.AllowGet);
                
            }
            catch
            {

MetricArts.JnJ.Mantenciones.Web/Views/KitRepuestos/AsociarRepuestos.cshtml
@model MetricArts.JnJ.Mantenciones.Models.Mantenedores.KitRepuestos.KitRepuestosViewModel
@{
    ViewBag.Title = "Asociar/Desasociar Repuestos";
}

<section class="container-fluid">
    <div class="row">
		    <ol class="breadcrumb">
			    <li><a href="@Url.Action("Index", "Home")">Inicio</a></li>
			    <li><a href="@Url.Action("Index", "Mantenedores")">Mantenedores</a></li>
				<li><a href="@Url.Action("Index", "KitRepuestos")">KIT Repuestos</a></li>
			</ol>
		</div>

				<div class="row-fluid">
					<h3>Asociar/Desasociar Repuestos <small>(KIT: @Model.kitRepuesto.Nombre , EQUIPO: @Model.kitRepuesto.Equipo.Nombre / @Model.kitRepuesto.Equipo.Sucursal.Cliente.Franquicia.NombreFranquicia - @Model.kitRepuesto.Equipo.Sucursal.Cliente.NombreEmpresa - @Model.kitRepuesto.Equipo.Sucursal.NombreSucursal)</small></h3>
				</div>
                @if (TempData["Mensaje"] != null && !String.IsNullOrEmpty(TempData["Mensaje"].ToString()))
                {
                <div class="alert alert-warning alert-dismissible fadeOutMantenedor" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <strong>@(TempData["Mensaje"])</strong>
                </div>
                }
                <br />
                <form action="@Url.Action("AsociarRepuestos", "KitRepuestos")" method="POST" class="form-horizontal">
                @Html.HiddenFor(x => x.FORM.IdKitRepuesto)
				<div class="row-fluid">
				    <div class="form-group">
						<div class="col-md-5">
                            <div class="no-seleccionable select">
                            <h4 align="center">Disponibles</h4>
                                <div style="height:300px;overflow-y:scroll">
					        <ul id="repuestos-disponibles" class="list-group">     
                                @for (int j = 0; j < Model.repuestosDisponibles.Count(); j++)
                                {
                                <li id="@(Model.repuestosDisponibles.ElementAt(j).IdRepuesto)" class="list-group-item">@Model.repuestosDisponibles.ElementAt(j).Codigo - @Model.repuestosDisponibles.ElementAt(j).Descripcion - @Model.repuestosDisponibles.ElementAt(j).Categoria - Cant.: @Model.repuestosDisponibles.ElementAt(j).Cantidad</li>               
                                }
                                
                                
						    </ul>
                            
                                <div id="vacio-disponibles">
                                @if (Model.repuestosDisponibles.Count() == 0) 
                                {
                                    <p class="list-group-item">No existen repuestos disponibles para este KIT</p>
                                }
                                    </div>

                                    </div>

                                </div>
                            <br />
                            <div id="boton-asociar">
                            
                                <button id="asociar-repuesto" type="button" class="btn btn-success">
						        
						        <span class="title">Asociar Seleccionado</span>
                                <span class="fa fa-angle-double-right"></span>
					        </button>
                            
                            </div>
                            
					    </div>
                        
                        <div class="col-md-2">
                            </div>

                        <div class="col-md-5">
                            <div class="no-seleccionable select">
                            <h4 align="center">Asociados</h4>
                                <div style="height:300px;overflow-y:scroll">
					        <ul id="repuestos-asociados" class="list-group">     
                                @for (int j = 0; j < Model.repuestosAsociados.Count(); j++)
                                {
                                <li id="@(Model.repuestosAsociados.ElementAt(j).IdRepuesto)" class="list-group-item">@Model.repuestosDisponibles.ElementAt(j).Codigo - @Model.repuestosDisponibles.ElementAt(j).Descripcion - @Model.repuestosDisponibles.ElementAt(j).Categoria - Cant.: @Model.repuestosDisponibles.ElementAt(j).Cantidad</li>               
                                }
                                
                                
						    </ul>
                                    
                                <div id="vacio-asociados">
                                @if (Model.repuestosAsociados.Count() == 0) 
                                {
                                    <p class="list-group-item">No existen repuestos asociados para este KIT</p>
                                }
                                    </div>
                                </div>
                                </div>
                            <br />
                            <div id="boton-desasociar">
                            
                                <button id="desasociar-repuesto" type="button" class="btn btn-primary pull-right">
						        <span class="fa fa-angle-double-left"></span>
						        <span class="title">Desasociar Seleccionado</span>
					        </button> 
                            
                            </div>

                        </div>
					</div>			
				</div>
                     @Html.HiddenFor(m => m.FORM.RepuestosIds)
                    <div class="row">
                        <br />
                        <br />
                    </div>
				<div class="row">
					<div class="col-md-6 col-md-offset-4">
						<button id="guardar-repuestos" type="button" class="btn btn-success">Guardar Cambios</button>
                        <a href="@Url.Action("Index", "KitRepuestos")" class="btn btn-primary">Cancelar</a>
					</div>
                    
				</div>
                </form>
			</section>
@Scripts.Render("~/bundles/custom/mantenedores/kitrepuestos/asociar-repuestos")
<script type="text/javascript">
    $(document).ready(function () {
        init();
    });
</script>

MetricArts.JnJ.Mantenciones.Web/Views/KitRepuestos/CrearNuevo.cshtml
@model MetricArts.JnJ.Mantenciones.Models.Mantenedores.KitRepuestos.KitRepuestosViewModel
@{
    ViewBag.Title = "Crear Nuevo KIT Repuestos";
}

<div class="row-fluid">
				<ol class="breadcrumb">
					<li><a href="@Url.Action("Index", "Home")">Inicio</a></li>
					<li><a href="@Url.Action("Index", "Mantenedores")">Mantenedores</a></li>
					<li><a href="@Url.Action("Index", "KitRepuestos")">Clientes</a></li>
					<li><a href="@Url.Action("CrearNuevo", "KitRepuestos")">Nuevo</a></li>
				</ol>
			</div>

			<section>
				<div class="row-fluid">
					<h3>Crear Nuevo KIT Repuestos</h3>
				</div>
                @if (TempData["Mensaje"] != null && !String.IsNullOrEmpty(TempData["Mensaje"].ToString()))
                {
                <div class="alert alert-warning alert-dismissible fadeOutMantenedor" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <strong>@(TempData["Mensaje"])</strong>
                </div>
                }
                <br />
                <form action="@Url.Action("CrearNuevo", "KitRepuestos")" method="POST" class="form-horizontal">
				<div class="row-fluid">

                    <div class="form-group">
							<label class="col-sm-4 control-label">@Html.LabelFor(x => x.FORM.Nombre)</label>
							<div class="col-sm-6">
                                @Html.TextBoxFor(x => x.FORM.Nombre, new { @class = "form-control input-sm" })
							</div>
						</div>
                    <hr />
                    <div class="form-group">
						    <label class="col-sm-4 control-label">@Html.LabelFor(x => x.FORM.IdFranquicia)</label>
							<div class="col-sm-6">
							    @Html.DropDownListFor(x => x.FORM.IdFranquicia, Model.Franquicias, "Seleccione una Franquicia", new { @class = "form-control input-sm" })
							</div>
						</div>
                        <div class="form-group">
						    <label class="col-sm-4 control-label">@Html.LabelFor(x => x.FORM.IdCliente)</label>
							<div class="col-sm-6">
							    <select id="FORM_IdCliente" class="form-control input-sm" disabled="disabled"></select>
							</div>
						</div>
                    <div class="form-group">
						    <label class="col-sm-4 control-label">@Html.LabelFor(x => x.FORM.IdSucursal)</label>
							<div class="col-sm-6">
							    <select id="FORM_IdSucursal" class="form-control input-sm" disabled="disabled"></select>
							</div>
						</div>

                    <div class="form-group">
                        <label class="col-sm-4 control-label">Equipos para asociar al KIT</label>
									<div class="col-md-6 no-seleccionable select">
										<ul id="equipos-planificacion" class="list-group small">
                                            <li class="list-group-item"><i>Debe escoger una Sucursal</i></li>
										</ul>
									</div>
                        @Html.HiddenFor(x => x.FORM.IdEquipo)
								</div>
                   @* <div class="form-group">
                        <label class="col-sm-4 control-label">Equipos asociados al KIT <small>(doble click para remover)</small></label>
									<div class="col-md-8 no-seleccionable select">
										<ul id="equipos-planificacion-asociados" class="list-group small">
                                            <li class="list-group-item">
                                                <i>No existen equipos asociados</i>
                                            </li>
										</ul>
									</div>
								</div>*@
                    
				</div>
				<div class="row">
					<div class="col-md-6 col-md-offset-4">
						<button id="crear-kit" type="button" class="btn btn-success pull-right">Guardar</button>
                        <a href="@Url.Action("Index", "KitRepuestos")" class="btn btn-primary">Cancelar</a>
					</div>
                    
				</div>
                </form>
			</section>
@Scripts.Render("~/bundles/custom/mantenedores/kitrepuestos/crear")
<script type="text/javascript">
    $(document).ready(function () {
        init('@Url.Action("ObtenerClientes", "ServicioConsulta")',
            '@Url.Action("ObtenerSucursales", "ServicioConsulta")',
            '@Url.Action("ObtenerEquiposSucursalKit", "ServicioConsulta")');
    });
</script>

MetricArts.JnJ.Mantenciones.Web/Views/KitRepuestos/Editar.cshtml
@model MetricArts.JnJ.Mantenciones.Models.Mantenedores.KitRepuestos.KitRepuestosViewModel
@{
    ViewBag.Title = "Editar KIT Repuestos";
}

<div class="row-fluid">
				<ol class="breadcrumb">
					<li><a href="@Url.Action("Index", "Home")">Inicio</a></li>
					<li><a href="@Url.Action("Index", "Mantenedores")">Mantenedores</a></li>
					<li><a href="@Url.Action("Index", "KitRepuestos")">Clientes</a></li>
					<li>Editar</li>
				</ol>
			</div>

			<section>
                
				<div class="row-fluid">
					<h3>Editar KIT Repuestos</h3>
				</div>
                @if (TempData["Mensaje"] != null && !String.IsNullOrEmpty(TempData["Mensaje"].ToString()))
                {
                <div class="alert alert-warning alert-dismissible fadeOutMantenedor" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <strong>@(TempData["Mensaje"])</strong>
                </div>
                }
                <br />
                <form action="@Url.Action("Editar", "KitRepuestos")" method="POST" class="form-horizontal">
                    @Html.HiddenFor(x => x.FORM.IdKitRepuesto)
				<div class="row-fluid">
						
                        <div class="form-group">
							<label class="col-sm-4 control-label">@Html.LabelFor(x => x.FORM.Nombre)</label>
							<div class="col-sm-6">
                                @Html.TextBoxFor(x => x.FORM.Nombre, new { @class = "form-control input-sm" })
							</div>
						</div>
																
				</div>
				<div class="row">
					<div class="col-md-6 col-md-offset-4">
						<input type="submit" class="btn btn-success pull-right" value="Guardar" />
                        <a href="@Url.Action("Index", "KitRepuestos")" class="btn btn-primary">Cancelar</a>
					</div>
				</div>
                </form>
			</section>
@Scripts.Render("~/bundles/custom/mantenedores/kitrepuestos/editar")
<script type="text/javascript">
    $(document).ready(function () {
        init();
    });
</script>